SUPABASE_URL = "https://erqkbyteeiihakagetad.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVycWtieXRlZWlpaGFrYWdldGFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2MTg1MzgsImV4cCI6MjA2ODE5NDUzOH0.hQjJZ3Xlk3nhk824ZJlOGfpokNg5e_f2_jbNP2I9Ass"
# Triggered commit
