SUPABASE_URL="https://fqgusikflxbvzvzepvty.supabase.co"
SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxZ3VzaWtmbHhidnp2emVwdnR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4NzA4MjcsImV4cCI6MjA3MDQ0NjgyN30.mnKl2bbPYSpwcP1bNKinECrodC8AOtOUUc2397-7Ka8"
COOKIE_PASSWORD="change-this"
